spring:
  session:
    store-type: redis
  redis:
    port: 12000
zuul: 
  retryable: true
  routes:
    order-management-ms:
      path: /order-management/**
      sensitiveHeaders: Authorization, Set-Cookie
security:
  user:
    name: gateway
    password: password